"""initial

Revision ID: 32cdc526d051
Revises: 
Create Date: 2026-08-26 12:37:17.589303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# data-model.md §0.3 — UPDATE/DELETE must never succeed against these four insert-only tables.
# Enforced at the DB role/trigger layer (constitution Principle VI / PLAN.md C6), not just by
# service-layer discipline.
INSERT_ONLY_TABLES = ("ticket_events", "audit_logs", "inbound_messages", "llm_calls")


def upgrade() -> None:
    # pgvector (semantic search, §1.22) and pg_trgm (Arabic/English fuzzy search, §1.10/§1.11/
    # §1.21) — required before any table below references vector(1024) or a gin_trgm_ops index.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('business_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('label_ar', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('permissions',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('label_ar', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('label_ar', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.CheckConstraint("code IN ('admin','lead','agent','customer')", name='ck_roles_code'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('api_keys',
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('departments',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('label_ar', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'code', name='uq_departments_branch_code')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_permission')
    )
    op.create_table('categories',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('label_ar', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('customer_type', sa.Text(), nullable=False),
    sa.Column('full_name_ar', sa.Text(), nullable=False),
    sa.Column('full_name_en', sa.Text(), nullable=True),
    sa.Column('national_id', sa.Text(), nullable=True),
    sa.Column('organization_name', sa.Text(), nullable=True),
    sa.Column('preferred_locale', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("customer_type IN ('individual','organization')", name='ck_customers_customer_type'),
    sa.CheckConstraint("preferred_locale IN ('ar','en')", name='ck_customers_preferred_locale'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_branch_dept_active', 'customers', ['branch_id', 'department_id', 'is_active'], unique=False)
    op.create_index('ix_customers_full_name_ar_trgm', 'customers', ['full_name_ar'], unique=False, postgresql_using='gin', postgresql_ops={'full_name_ar': 'gin_trgm_ops'})
    op.create_index('ix_customers_full_name_en_trgm', 'customers', ['full_name_en'], unique=False, postgresql_using='gin', postgresql_ops={'full_name_en': 'gin_trgm_ops'})
    op.create_index('ix_customers_organization_name_trgm', 'customers', ['organization_name'], unique=False, postgresql_using='gin', postgresql_ops={'organization_name': 'gin_trgm_ops'})
    op.create_table('priorities',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('label_ar', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'department_id', 'code', name='uq_priorities_branch_dept_code')
    )
    op.create_table('teams',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('label_ar', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_statuses',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('pauses_sla', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('label_ar', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'department_id', 'code', name='uq_ticket_statuses_branch_dept_code')
    )
    op.create_table('users',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name_ar', sa.Text(), nullable=False),
    sa.Column('full_name_en', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('locale', sa.Text(), server_default='ar', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("locale IN ('ar','en')", name='ck_users_locale'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_branch_active', 'users', ['branch_id', 'is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor_created', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_correlation_id', 'audit_logs', ['correlation_id'], unique=False)
    op.create_index('ix_audit_logs_entity_created', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('channel_configs',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('default_category_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("channel IN ('web','email','whatsapp','sms','chat','portal')", name='ck_channel_configs_channel'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['default_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('contact_methods',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("kind IN ('phone','email','whatsapp','other')", name='ck_contact_methods_kind'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contact_methods_value_trgm', 'contact_methods', ['value'], unique=False, postgresql_using='gin', postgresql_ops={'value': 'gin_trgm_ops'})
    op.create_index('uq_contact_methods_primary_per_customer', 'contact_methods', ['customer_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_table('kb_articles',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('title_ar', sa.Text(), nullable=False),
    sa.Column('title_en', sa.Text(), nullable=False),
    sa.Column('body_ar', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('helpful_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'slug', name='uq_kb_articles_branch_slug')
    )
    op.create_index('ix_kb_articles_body_ar_trgm', 'kb_articles', ['body_ar'], unique=False, postgresql_using='gin', postgresql_ops={'body_ar': 'gin_trgm_ops'})
    op.create_index('ix_kb_articles_body_en_trgm', 'kb_articles', ['body_en'], unique=False, postgresql_using='gin', postgresql_ops={'body_en': 'gin_trgm_ops'})
    op.create_index('ix_kb_articles_category_id', 'kb_articles', ['category_id'], unique=False)
    op.create_table('quick_replies',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('body_ar', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('label_ar', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_policies',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('priority_id', sa.UUID(), nullable=True),
    sa.Column('first_response_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_minutes', sa.Integer(), nullable=False),
    sa.Column('business_hours_only', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('label_ar', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['priority_id'], ['priorities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sla_policies_resolution_order', 'sla_policies', ['branch_id', 'department_id', 'category_id', 'priority_id'], unique=False)
    op.create_table('status_transitions',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('from_status_id', sa.UUID(), nullable=False),
    sa.Column('to_status_id', sa.UUID(), nullable=False),
    sa.Column('required_permission', sa.Text(), nullable=True),
    sa.Column('requires_reason', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_status_id'], ['ticket_statuses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_status_id'], ['ticket_statuses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'department_id', 'from_status_id', 'to_status_id', name='uq_status_transitions_scope_from_to')
    )
    op.create_table('team_members',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_members_team_user')
    )
    op.create_table('user_roles',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'branch_id', 'department_id', name='uq_user_roles_user_role_scope')
    )
    op.create_table('kb_article_chunks',
    sa.Column('kb_article_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("locale IN ('ar','en')", name='ck_kb_article_chunks_locale'),
    sa.ForeignKeyConstraint(['kb_article_id'], ['kb_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_article_id', 'locale', 'chunk_index', name='uq_kb_article_chunks_article_locale_index')
    )
    op.create_index('ix_kb_article_chunks_content_trgm', 'kb_article_chunks', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.create_index('ix_kb_article_chunks_embedding_hnsw', 'kb_article_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('tickets',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('reference_no', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('priority_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('source_locale', sa.Text(), nullable=False),
    sa.Column('sla_policy_id', sa.UUID(), nullable=True),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sla_paused_ms', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('needs_triage', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ai_suggested_category_id', sa.UUID(), nullable=True),
    sa.Column('ai_category_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('csat_score', sa.Integer(), nullable=True),
    sa.Column('csat_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("channel IN ('web','email','whatsapp','sms','chat','portal')", name='ck_tickets_channel'),
    sa.CheckConstraint("source_locale IN ('ar','en')", name='ck_tickets_source_locale'),
    sa.ForeignKeyConstraint(['ai_suggested_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['priority_id'], ['priorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sla_policy_id'], ['sla_policies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['ticket_statuses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_no')
    )
    op.create_index('ix_tickets_assignee_status', 'tickets', ['assignee_id', 'status_id'], unique=False)
    op.create_index('ix_tickets_branch_dept_status', 'tickets', ['branch_id', 'department_id', 'status_id'], unique=False)
    op.create_index('ix_tickets_created_at', 'tickets', ['created_at'], unique=False)
    op.create_index('ix_tickets_needs_triage', 'tickets', ['status_id'], unique=False, postgresql_where=sa.text('needs_triage'))
    op.create_index('ix_tickets_team_status', 'tickets', ['team_id', 'status_id'], unique=False)
    op.create_index('ix_tickets_unassigned_queue', 'tickets', ['department_id', 'status_id'], unique=False, postgresql_where=sa.text('assignee_id IS NULL'))
    op.create_table('attachments',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('num_nonnulls(ticket_id, customer_id) = 1', name='ck_attachments_exactly_one_owner'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_attachments_customer_id', 'attachments', ['customer_id'], unique=False)
    op.create_index('ix_attachments_ticket_id', 'attachments', ['ticket_id'], unique=False)
    op.create_table('inbound_messages',
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("channel IN ('web','email','whatsapp','sms','chat','portal')", name='ck_inbound_messages_channel'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'external_id', name='uq_inbound_messages_channel_external_id')
    )
    op.create_index('ix_inbound_messages_ticket_id', 'inbound_messages', ['ticket_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('capability', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("capability IN ('categorize','summarize','suggest_reply','suggest_solution')", name='ck_llm_calls_capability'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_calls_capability_created', 'llm_calls', ['capability', 'created_at'], unique=False)
    op.create_index('ix_llm_calls_ticket_created', 'llm_calls', ['ticket_id', 'created_at'], unique=False)
    op.create_table('ticket_events',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("event_type IN ('created', 'status_changed', 'assigned', 'reassigned', 'field_changed', 'note_added', 'reply_sent', 'attachment_added', 'sla_breached', 'reopened', 'ai_suggestion_applied')", name='ck_ticket_events_event_type'),
    sa.CheckConstraint("visibility IN ('internal','customer')", name='ck_ticket_events_visibility'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_events_correlation_id', 'ticket_events', ['correlation_id'], unique=False)
    op.create_index('ix_ticket_events_ticket_created', 'ticket_events', ['ticket_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # data-model.md §0.1/§0.2 — created_by/updated_by FKs, added after every table exists.
    # use_alter=True on these FKs (app/models/base.py) defers them past the branches<->users
    # cycle, but SQLAlchemy's DDL compiler excludes use_alter constraints from CREATE TABLE
    # and op.create_table does not auto-emit the follow-up ALTER the way MetaData.create_all()
    # does — so they are added explicitly here, once every table exists.
    op.create_foreign_key('fk_branches_created_by_users', 'branches', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_branches_updated_by_users', 'branches', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_departments_created_by_users', 'departments', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_departments_updated_by_users', 'departments', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_users_created_by_users', 'users', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_users_updated_by_users', 'users', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_roles_created_by_users', 'roles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_roles_updated_by_users', 'roles', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_permissions_created_by_users', 'permissions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_permissions_updated_by_users', 'permissions', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_role_permissions_created_by_users', 'role_permissions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_role_permissions_updated_by_users', 'role_permissions', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_user_roles_created_by_users', 'user_roles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_user_roles_updated_by_users', 'user_roles', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_teams_created_by_users', 'teams', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_teams_updated_by_users', 'teams', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_team_members_created_by_users', 'team_members', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_team_members_updated_by_users', 'team_members', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_customers_created_by_users', 'customers', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_customers_updated_by_users', 'customers', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_contact_methods_created_by_users', 'contact_methods', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_contact_methods_updated_by_users', 'contact_methods', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_categories_created_by_users', 'categories', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_categories_updated_by_users', 'categories', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_priorities_created_by_users', 'priorities', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_priorities_updated_by_users', 'priorities', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_ticket_statuses_created_by_users', 'ticket_statuses', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_ticket_statuses_updated_by_users', 'ticket_statuses', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_status_transitions_created_by_users', 'status_transitions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_status_transitions_updated_by_users', 'status_transitions', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_tickets_created_by_users', 'tickets', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_tickets_updated_by_users', 'tickets', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_ticket_events_created_by_users', 'ticket_events', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_attachments_created_by_users', 'attachments', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_attachments_updated_by_users', 'attachments', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_sla_policies_created_by_users', 'sla_policies', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_sla_policies_updated_by_users', 'sla_policies', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_quick_replies_created_by_users', 'quick_replies', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_quick_replies_updated_by_users', 'quick_replies', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_kb_articles_created_by_users', 'kb_articles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_kb_articles_updated_by_users', 'kb_articles', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_kb_article_chunks_created_by_users', 'kb_article_chunks', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_kb_article_chunks_updated_by_users', 'kb_article_chunks', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_api_keys_created_by_users', 'api_keys', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_api_keys_updated_by_users', 'api_keys', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_audit_logs_created_by_users', 'audit_logs', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_inbound_messages_created_by_users', 'inbound_messages', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_channel_configs_created_by_users', 'channel_configs', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_channel_configs_updated_by_users', 'channel_configs', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_llm_calls_created_by_users', 'llm_calls', 'users', ['created_by'], ['id'], ondelete='SET NULL')

    # tickets.reference_no format TKT-{YYYY}-{6-digit sequence} (data-model.md §1.16) — the
    # numeric part is DB-sequence-generated; TicketService formats the full string at insert time.
    op.execute("CREATE SEQUENCE ticket_reference_seq AS BIGINT START WITH 1 INCREMENT BY 1")

    # Constitution Principle VI / PLAN.md C6 — revoke UPDATE/DELETE on the four insert-only
    # tables at the DB role/trigger layer, not just by service-layer discipline.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION reject_insert_only_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% is insert-only: % is not permitted', TG_TABLE_NAME, TG_OP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table_name in INSERT_ONLY_TABLES:
        op.execute(
            f"""
            CREATE TRIGGER trg_{table_name}_insert_only
            BEFORE UPDATE OR DELETE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION reject_insert_only_mutation()
            """
        )


def downgrade() -> None:
    for table_name in INSERT_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table_name}_insert_only ON {table_name}")
    op.execute("DROP FUNCTION IF EXISTS reject_insert_only_mutation()")
    op.execute("DROP SEQUENCE IF EXISTS ticket_reference_seq")

    # Drop the created_by/updated_by FKs before the tables themselves are dropped below.
    op.drop_constraint('fk_llm_calls_created_by_users', 'llm_calls', type_='foreignkey')
    op.drop_constraint('fk_channel_configs_updated_by_users', 'channel_configs', type_='foreignkey')
    op.drop_constraint('fk_channel_configs_created_by_users', 'channel_configs', type_='foreignkey')
    op.drop_constraint('fk_inbound_messages_created_by_users', 'inbound_messages', type_='foreignkey')
    op.drop_constraint('fk_audit_logs_created_by_users', 'audit_logs', type_='foreignkey')
    op.drop_constraint('fk_api_keys_updated_by_users', 'api_keys', type_='foreignkey')
    op.drop_constraint('fk_api_keys_created_by_users', 'api_keys', type_='foreignkey')
    op.drop_constraint('fk_kb_article_chunks_updated_by_users', 'kb_article_chunks', type_='foreignkey')
    op.drop_constraint('fk_kb_article_chunks_created_by_users', 'kb_article_chunks', type_='foreignkey')
    op.drop_constraint('fk_kb_articles_updated_by_users', 'kb_articles', type_='foreignkey')
    op.drop_constraint('fk_kb_articles_created_by_users', 'kb_articles', type_='foreignkey')
    op.drop_constraint('fk_quick_replies_updated_by_users', 'quick_replies', type_='foreignkey')
    op.drop_constraint('fk_quick_replies_created_by_users', 'quick_replies', type_='foreignkey')
    op.drop_constraint('fk_sla_policies_updated_by_users', 'sla_policies', type_='foreignkey')
    op.drop_constraint('fk_sla_policies_created_by_users', 'sla_policies', type_='foreignkey')
    op.drop_constraint('fk_attachments_updated_by_users', 'attachments', type_='foreignkey')
    op.drop_constraint('fk_attachments_created_by_users', 'attachments', type_='foreignkey')
    op.drop_constraint('fk_ticket_events_created_by_users', 'ticket_events', type_='foreignkey')
    op.drop_constraint('fk_tickets_updated_by_users', 'tickets', type_='foreignkey')
    op.drop_constraint('fk_tickets_created_by_users', 'tickets', type_='foreignkey')
    op.drop_constraint('fk_status_transitions_updated_by_users', 'status_transitions', type_='foreignkey')
    op.drop_constraint('fk_status_transitions_created_by_users', 'status_transitions', type_='foreignkey')
    op.drop_constraint('fk_ticket_statuses_updated_by_users', 'ticket_statuses', type_='foreignkey')
    op.drop_constraint('fk_ticket_statuses_created_by_users', 'ticket_statuses', type_='foreignkey')
    op.drop_constraint('fk_priorities_updated_by_users', 'priorities', type_='foreignkey')
    op.drop_constraint('fk_priorities_created_by_users', 'priorities', type_='foreignkey')
    op.drop_constraint('fk_categories_updated_by_users', 'categories', type_='foreignkey')
    op.drop_constraint('fk_categories_created_by_users', 'categories', type_='foreignkey')
    op.drop_constraint('fk_contact_methods_updated_by_users', 'contact_methods', type_='foreignkey')
    op.drop_constraint('fk_contact_methods_created_by_users', 'contact_methods', type_='foreignkey')
    op.drop_constraint('fk_customers_updated_by_users', 'customers', type_='foreignkey')
    op.drop_constraint('fk_customers_created_by_users', 'customers', type_='foreignkey')
    op.drop_constraint('fk_team_members_updated_by_users', 'team_members', type_='foreignkey')
    op.drop_constraint('fk_team_members_created_by_users', 'team_members', type_='foreignkey')
    op.drop_constraint('fk_teams_updated_by_users', 'teams', type_='foreignkey')
    op.drop_constraint('fk_teams_created_by_users', 'teams', type_='foreignkey')
    op.drop_constraint('fk_user_roles_updated_by_users', 'user_roles', type_='foreignkey')
    op.drop_constraint('fk_user_roles_created_by_users', 'user_roles', type_='foreignkey')
    op.drop_constraint('fk_role_permissions_updated_by_users', 'role_permissions', type_='foreignkey')
    op.drop_constraint('fk_role_permissions_created_by_users', 'role_permissions', type_='foreignkey')
    op.drop_constraint('fk_permissions_updated_by_users', 'permissions', type_='foreignkey')
    op.drop_constraint('fk_permissions_created_by_users', 'permissions', type_='foreignkey')
    op.drop_constraint('fk_roles_updated_by_users', 'roles', type_='foreignkey')
    op.drop_constraint('fk_roles_created_by_users', 'roles', type_='foreignkey')
    op.drop_constraint('fk_users_updated_by_users', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_created_by_users', 'users', type_='foreignkey')
    op.drop_constraint('fk_departments_updated_by_users', 'departments', type_='foreignkey')
    op.drop_constraint('fk_departments_created_by_users', 'departments', type_='foreignkey')
    op.drop_constraint('fk_branches_updated_by_users', 'branches', type_='foreignkey')
    op.drop_constraint('fk_branches_created_by_users', 'branches', type_='foreignkey')


    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_events_ticket_created', table_name='ticket_events')
    op.drop_index('ix_ticket_events_correlation_id', table_name='ticket_events')
    op.drop_table('ticket_events')
    op.drop_index('ix_llm_calls_ticket_created', table_name='llm_calls')
    op.drop_index('ix_llm_calls_capability_created', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index('ix_inbound_messages_ticket_id', table_name='inbound_messages')
    op.drop_table('inbound_messages')
    op.drop_index('ix_attachments_ticket_id', table_name='attachments')
    op.drop_index('ix_attachments_customer_id', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('ix_tickets_unassigned_queue', table_name='tickets', postgresql_where=sa.text('assignee_id IS NULL'))
    op.drop_index('ix_tickets_team_status', table_name='tickets')
    op.drop_index('ix_tickets_needs_triage', table_name='tickets', postgresql_where=sa.text('needs_triage'))
    op.drop_index('ix_tickets_created_at', table_name='tickets')
    op.drop_index('ix_tickets_branch_dept_status', table_name='tickets')
    op.drop_index('ix_tickets_assignee_status', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_kb_article_chunks_embedding_hnsw', table_name='kb_article_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_kb_article_chunks_content_trgm', table_name='kb_article_chunks', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.drop_table('kb_article_chunks')
    op.drop_table('user_roles')
    op.drop_table('team_members')
    op.drop_table('status_transitions')
    op.drop_index('ix_sla_policies_resolution_order', table_name='sla_policies')
    op.drop_table('sla_policies')
    op.drop_table('quick_replies')
    op.drop_index('ix_kb_articles_category_id', table_name='kb_articles')
    op.drop_index('ix_kb_articles_body_en_trgm', table_name='kb_articles', postgresql_using='gin', postgresql_ops={'body_en': 'gin_trgm_ops'})
    op.drop_index('ix_kb_articles_body_ar_trgm', table_name='kb_articles', postgresql_using='gin', postgresql_ops={'body_ar': 'gin_trgm_ops'})
    op.drop_table('kb_articles')
    op.drop_index('uq_contact_methods_primary_per_customer', table_name='contact_methods', postgresql_where=sa.text('is_primary'))
    op.drop_index('ix_contact_methods_value_trgm', table_name='contact_methods', postgresql_using='gin', postgresql_ops={'value': 'gin_trgm_ops'})
    op.drop_table('contact_methods')
    op.drop_table('channel_configs')
    op.drop_index('ix_audit_logs_entity_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_correlation_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_branch_active', table_name='users')
    op.drop_table('users')
    op.drop_table('ticket_statuses')
    op.drop_table('teams')
    op.drop_table('priorities')
    op.drop_index('ix_customers_organization_name_trgm', table_name='customers', postgresql_using='gin', postgresql_ops={'organization_name': 'gin_trgm_ops'})
    op.drop_index('ix_customers_full_name_en_trgm', table_name='customers', postgresql_using='gin', postgresql_ops={'full_name_en': 'gin_trgm_ops'})
    op.drop_index('ix_customers_full_name_ar_trgm', table_name='customers', postgresql_using='gin', postgresql_ops={'full_name_ar': 'gin_trgm_ops'})
    op.drop_index('ix_customers_branch_dept_active', table_name='customers')
    op.drop_table('customers')
    op.drop_table('categories')
    op.drop_table('role_permissions')
    op.drop_table('departments')
    op.drop_table('api_keys')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('branches')
    # ### end Alembic commands ###
